### ISSUE TITLE
Use Emoji-Button in Static Site?

### ISSUE THREAD

**Issue by toddwords** [joeattardi/picmo#135]
This is a really great project and the best looking and up-to-date picker out there from what I can tell. Do you have any advice on getting this to run on a static site in the browser so I can use it outside of a node project?

**Comment by joeattardi** [comment]
Hi, thanks for your feedback about the project!

In the current version, it is only distributed as an ES Module. This means it can be used outside of a node project, but will only work on browsers that support ES Modules. Not sure what your browser support requirements are, but currently ES Modules are supported in all major browsers except for IE11. Emoji Button wouldn't work in IE11 anyway because it uses CSS variables which also are not supported. 

So, if you want to target modern browsers it is definitely possible to pull the module in via just a `script` tag.

**Comment by q2apro** [comment]
If you could provide a `dist` folder with the necessary JS and CSS files, it would be very helpful. 

Otherwise I and many others that are not familiar with NodeJS cannot use it.

**Comment by ctstacey** [comment]
I thought an example might help.

Use something like:
(placed after the HTML element with 'trigger' class)

<pre><code>
    <script type="module">
       import { EmojiButton } from 'https://cdn.jsdelivr.net/npm/@joeattardi/emoji-button@4.6.0';

        const picker = new EmojiButton({autoHide:false});
        const trigger = document.querySelector('.trigger');

        picker.on('emoji', selection => {
          trigger.textContent = selection.emoji;
        });

        trigger.addEventListener('click', () => picker.togglePicker(trigger));
    </script>
</code></pre>

**Comment by joeattardi** [comment]
More to come on this. Looking back now I think it was a mistake to change this library so that it could _only_ be consumed as an ES module.

Someone submitted a PR with this idea and I admit I was interested at the time, though since then I have heard from several people who have had headaches getting the library working in their project in this way.

So for version 5, which I am working on now, I am most likely going to be going back to offering a CommonJS and/or UMD module as well for better interoperability.

**Comment by collimarco** [comment]
Yes, this is much needed. 

It would be great if we could use this in a Rails application, like a normal Javascript library. 

Currently it seems impossible to use it within Rails: many npm dependencies, TS files, ... 

If we had a single Javascript file in `dist`, like `emoji-button.min.js` with everything included, that would make the usage of this library trivial.

**Comment by joeattardi** [comment]
There is still a bit of work left unfortunately- life got in the way for a while - but hopefully version 5 will be available soon. 

Version 5 will be getting split into multiple independent packages. There will be the core package, an emoji-data package, and two renderers to choose from: native emojis or Twemoji. 

This means you will have several JS files to pull in but if they all have a UMD distribution you should be able to use them that way. 

Out of curiosity, what browsers are you supporting with your app?

If you need to support IE11 then Emoji Button is a no go anyway, otherwise native ES Module support is pretty good now: https://caniuse.com/es6-module

**Comment by collimarco** [comment]
@joeattardi Thanks for the reply! 

We only need to support modern browsers, not an issue for IE or old versions. 

However the main problem is the integration with a Rails application entirely built with [Rails asset pipeline](https://guides.rubyonrails.org/asset_pipeline.html). Basically all Javascript files and JS libraries are built in a single, large JS file that doesn't use ES modules. 

For example. talking about a library similar to this one, we do `yarn add packagename` and then `//= require packagename/dist/packagename.min.js` (the `require` imports / copy the library code at compile time, it's not JS).

**Comment by drkrtj** [comment]
Hello Joe, great project. I too am having problems with version 4 (npm). I have to use 3.0.3 until your non npm version is released. Any update on version 5? It is currently March of 2022. 

Thanks

**Comment by joeattardi** [comment]
It's not clear yet but I hope to have a beta ready soon. I know it's slow going. I've got a lot going on right now and this is a one person project 😃

What's the issue you are having with v4? Maybe there is an interim solution.

**Comment by drkrtj** [comment]
I am currently using the CDN for version 3. I am not proficient on node or npm so I am having general installation issues. I would really like to use the custom emojis for gif files but 3 does not have that feature.

**Comment by joeattardi** [comment]
4.x is also available via CDN and can be used without npm. It's exposed as an ES module which you can import directly. I can show an example for you later when I'm at my desk.

**Comment by drkrtj** [comment]
That sounds great. When you are free I would love to see it. Thanks

**Comment by joeattardi** [comment]
Here's a pretty basic example, using the latest version from a CDN (no npm required):

https://codepen.io/thinksInCode/pen/KKZWYaE

The picker is imported directly as an ES module. Currently, to consume Emoji Button without using npm or a bundler, you'll have to use this approach.

You can click the button to show the picker, then when you select an emoji it will be set as the button's value. Simple example but I hope it helps.

**Comment by drkrtj** [comment]
Thanks Joe,
 I am able to get it to work as expected only in firefox(Other browsers are acting strange) However, I am not able to get the emoji to be placed into the input. I am using:

picker.on('emoji', emoji => {
 document.querySelector('#message_input').value += emoji;
 });


but it is not functioning. Any suggestions?

 Thanks
     On Saturday, March 26, 2022, 08:53:16 PM PDT, Joe Attardi ***@***.***> wrote:  
 
 


Here's a pretty basic example, using the latest version from a CDN (no npm required):

https://codepen.io/thinksInCode/pen/KKZWYaE

The picker is imported directly as an ES module. Currently, to consume Emoji Button without using npm or a bundler, you'll have to use this approach.

You can click the button to show the picker, then when you select an emoji it will be set as the button's value. Simple example but I hope it helps.

**Comment by drkrtj** [comment]
Thanks Joe,
     I am able to get it to work as expected only in firefox(Other browsers are acting strange) However, I am not able to get the emoji to be placed into the input. I am using:

picker.on('emoji', emoji => {
      document.querySelector('#message_input').value += emoji;
  });


but it is not functioning. Any suggestions?

           Thanks

**Comment by joeattardi** [comment]
Does an error get thrown, or does nothing happen?

**Comment by drkrtj** [comment]
The error is for the custom image(gif). The error is "undefined".

**Comment by joeattardi** [comment]
If it's a custom emoji, the selection passed to the event will have a `url` property, which you'll need to then put in an `img` tag. You can't add a custom emoji (or any image, that is) to an input field as you have indicated above.

**Comment by joeattardi** [comment]
PicMo 5 will include standalone ESM and UMD builds for use cases that don't use npm or a bundler

**Comment by drkrtj** [comment]
That sounds great.

**Comment by joeattardi** [comment]
This issue is resolved in `v5.0.0-beta.6`.

**Comment by joeattardi** [comment]
As I said above, you can't put a custom emoji into an input field since it's an image. You'll need an `img` tag, and set the `src` to the value of the `url` property of the emoji selection.

**Comment by drkrtj** [comment]
Thanks Joe!


     On Tuesday, October 11, 2022, 09:37:28 AM PDT, Joe Attardi ***@***.***> wrote:  
 
 


As I said above, you can't put a custom emoji into an input field since it's an image. You'll need an img tag, and set the src to the value of the url property of the emoji selection.
