### ISSUE TITLE
emojiVersion not detecting supported Emoji version

### ISSUE THREAD

**Issue by kelvilee** [joeattardi/picmo#191]
Hello 👋  I've been testing the emoji picker on different operating systems and it seems like the rendering test is not detecting the correct emoji version to use. I'm using the default setting for `emojiVersion` and have successfully created a picker with the latest Emoji version 14.0 on MacOS 12.3.1

Examples:
MacOS Monterey 12.3.1
![image](https://user-images.githubusercontent.com/33191320/168171729-a08ef366-6d8a-42a9-86eb-17fd14ea2c3e.png)

MacOS Catalina 10.15.6 (Looks like it's using Emoji version 13.0)
![image](https://user-images.githubusercontent.com/33191320/168171756-03cae910-d45b-48ff-9ede-96eb51f9e289.png)

Windows 10 (Looks like it's using Emoji version 13.0)
![image](https://user-images.githubusercontent.com/33191320/168171785-7459f216-9ad5-4730-b865-89b0a493533f.png)

**Comment by joeattardi** [comment]
Thanks for trying the beta and reporting this!

I think I need to tweak the emoji version detection. Right now it checks the database for a given version and grabs the first emoji included in that version. If that renders ok, it assumes it's supported.

There's no real good way to check emoji rendering support. I am following the approach shown [here](https://gist.github.com/mathisonian/7885295). Problem is, some new emojis are actually sequences formed by existing emojis. If one of the emojis in that sequence is supported, but the new sequence is not, it still looks like it rendered ok.

I went through and changed it so that the "test emoji" for each version is a single code point, but there are still two versions (13.1 and 12.1) that _only_ contain sequences.

I'm trying to find a way to test the rendering of these ones - otherwise, to prevent false positives like shown here, only versions with single emoji code points will be automatically checked.

Will update here when the fix is done! 

Thanks again!

**Comment by joeattardi** [comment]
I was unfortunately not able to find a good way to check the sequences, so I had to remove 13.1 and 12.1 from the auto detection. This may mean that the auto detection chooses a slightly older version than is supported (13 instead of 13.1, 12 instead of 12.1) but I suppose that's better than the current situation where it shows unsupported emojis.

I just published 5.0.0-beta.9 which includes this change. Now it only compares against known single code point emojis.

Feel free to reopen if you still run into issues, thanks! I applied for an open source BrowserStack license so I am hoping I will have an easier time doing older browser/OS testing soon.
