### ISSUE TITLE
Alternative emoji storage

### ISSUE THREAD

**Issue by hognevevle** [joeattardi/picmo#199]
Hi there!

Love the work you've put into this 🙏 

Because our app is being embedded on 3rd party sites using an iframe, IndexedDB is not always available, e.g. if the browser is in incognito/private mode. This, unfortunately, causes picmo to crash.

![CleanShot 2022-05-18 at 14 53 53](https://user-images.githubusercontent.com/2721188/169043187-4f2fcb48-5088-4788-9dbc-806b459cd699.png)

![CleanShot 2022-05-18 at 14 54 14](https://user-images.githubusercontent.com/2721188/169043303-c696aa7a-c3eb-4e31-85a3-77332f073542.png)

Any way to provide a fallback behaviour in the case when IndexedDB is not available?

**Comment by joeattardi** [comment]
Thanks for filing this! Unfortunately this seems to be a use case I overlooked. I guess I didn't realize that iframes didn't always support IndexedDB.

Unfortunately there isn't an alternative. There may be an IndexedDB polyfill available but I'm not sure? Either way, for such cases I think I can have a solution for this in a day or two.

For these cases we could just have an in memory data store. It's not super efficient and will require everything to be kept in memory. Since it won't stay cached there's little benefit to downloading from the CDN in that case since you'll have to redownload it each time.

I'm thinking maybe an additional package that bundles the emoji data from `emojibase` coupled with a very simple in memory store. I can add a new picker option for this data store, and if one is specified it won't attempt to use IndexedDB. 

Maybe not the most ideal, not sure. What do you think?

**Comment by hognevevle** [comment]
Many thanks for the feedback, and no worries; I do realize this is a bit of an edge case. I expect it to only affect a very small percentage of users, so I'm not too concerned about it perhaps being slightly suboptimal for them (as long as "it works"). I think therefore your proposal sounds good 🙂

**Comment by joeattardi** [comment]
Fixed in 5.1.0!
