### ISSUE TITLE
Uncaught TypeError: picmo.createPopup is not a function

### ISSUE THREAD

**Issue by peremarshall** [joeattardi/picmo#205]
This is such a great resource. Thanks so much for all of your hard work.

I'm attempting to create a popup , and installing PicMo via CDN using <script> tags...

```
<script src="https://unpkg.com/picmo@5.1.0/dist/umd/picmo.js"></script>
<script src="https://unpkg.com/@picmo/popup-picker@5.1.0/dist/umd/picmo-popup.js"></script>
```

If I create an inline picker, everything works great...

```
const rootElement = document.querySelector('#pickerTrigger');
const picker = picmo.createPicker({
  rootElement: rootElement
});
```
  
  If I try to create a popup picker, I get errors that "picmo.createPopup" is undefined.
  
```
const rootElement = document.querySelector('#pickerTrigger');
const picker = picmo.createPopup({
  referenceElement: rootElement,
  triggerElement: rootElement
});
```

Any idea what's wrong?

Also... the documentation seems to be a little inconsistent, sometimes implying that a popup is still created with createPicker, and sometimes stating that a popup is created with createPopup.

Thanks so much. Let me know if there is anything I can do to help.

**Comment by joeattardi** [comment]
Thanks for reporting this! Looks like I missed a spot when updating the documentation after splitting the packages up. For example, the API docs for `createPopup` (https://picmojs.com/docs/api/popup-picker/functions/create-popup) still show the function name as `createPicker`. 

Feel free to open a PR with the documentation fix; otherwise, I will try to get it updated in the next day or two. 

As for your question, `createPopup` is exported by the `@picmo/popup-picker` module. If you're using the UMD version as your post suggests, this is available from `picmoPopup.createPopup`. The `picmo-popup.js` file exports the `picmoPopup` namespace.

I hope this helps!

**Comment by peremarshall** [comment]
Thanks so much. Using that namespace worked great.

I would love to help update the documentation, but I've also noticed that the `createPopup` method sometimes accepts one argument in the documentation, and sometimes accepts two.

Here it just shows one argument, at the bottom of the page...

https://picmojs.com/docs/usage/creating-pickers

Since I'm not very familiar with the library yet, I'd be nervous that my edits wouldn't be accurate.

Thanks again.

**Comment by joeattardi** [comment]
No worries! I just published an update to the documentation and the incorrect entries should be fixed now!
Thanks for finding that.
