### ISSUE TITLE
Picker with twemoji is extremely slow in chromium based browsers

### ISSUE THREAD

**Issue by Zheoni** [joeattardi/picmo#210]
[This demo](https://picmojs.com/storybook/?path=/story/emoji-picker--twemoji) for me and a friend is very slow to the point it's unusable in (at least) chrome, brave and edge; in **firefox it's ok**.
It only happens with twemoji, native emojis are fine.
Implemented in my own codebase the issue is the same.

I'm not very experienced in interpreting the performance tab but it seems something is blocking the main thread causing fps drops in the page when interacting (even hovering) with the picker.

![image](https://user-images.githubusercontent.com/38019254/172025856-209067c9-1da3-4f60-b2f6-37108bbe9475.png)

**Comment by joeattardi** [comment]
I will be the first to admit that in general there are performance problems with the Twemoji renderer. 

Unfortunately, Twemoji does not provide a sprite sheet. It's been requested many times in the past but they always push back on it.

I had wanted to do some experiments with building my own SVG sprite sheet using the individual Twemoji images; however, I ended up postponing this because I was getting burned out working on version 5 for so long. There may be some other changes that can help such as lazily loading all images in a category when that category is scrolled to/selected; that will load a lot of images up front but may be more performant for scrolling purposes.

Anyway, Twemoji improvements including further sprite sheet investigation is definitely on the roadmap, currently slated for version 6. No timeline on that yet - I am still recovering from all the time spent getting version 5 out :)

I can do a performance capture as well and see if there's anything obvious I missed that could be fixed! Otherwise I'd say if you're having performance issues, native emojis may be the way to go for now.

**Comment by joeattardi** [comment]
Update! I am close to having a working Twemoji renderer that uses sprite sheets! 

Testing so far, it runs so much more smoothly than the current one. It creates sprite sheets of each emoji category. So as you scroll, it's already there, it doesn't start loading hundreds of images at once.

Hopefully will have a new release with this soon.

**Comment by joeattardi** [comment]
Just released 5.3.0 which has a new Twemoji renderer which uses sprite sheets!
