### ISSUE TITLE
"LocalStorage is not defined error" in Nuxt+Webpack environment

### ISSUE THREAD

**Issue by marquizzo** [joeattardi/picmo#214]
**Versions**
`"picmo": "^5.2.0"`

**Reproduction**
https://codesandbox.io/s/awesome-shaw-qh2utg?file=/pages/index.vue

**Steps to reproduce**
I'm running into two issues:
1. I'm running picmo in Nuxt.js v 2.15. When I used `import { createPicker } from "picmo";`, I got an error:
    > "Must use import to load ES Module" 

    which I solved by adding `transpile: ['picmo']` to nuxt.config.js as suggested [in this discussion](https://github.com/nuxt/nuxt.js/issues/9223#issuecomment-834832352). However, that solution yields to a new error:
2. Now upon using `import { createPicker } from "picmo";`, I immediately get a runtime error: 
    > localStorage is not defined

You can see this error in action by visiting the codesandbox link above. If you click on the [  ] Show all Frames checkbox, you'll see that the error comes from `node_modules/picmo/dist/index.js:1: `. It seems that the `localStorage` is expected to be available upon import, so I don't get time to wait until the component is `mounted()`. How can I fix this issue?

**Comment by joeattardi** [comment]
I think the problem is for some reason Nuxt is trying to run the PicMo code on the server side. This won't work - PicMo has dependencies on client side APIs like IndexedDB and localStorage so it must only run on the client.

Normally localStorage isn't accessed until creating a picker so I'm not sure why just importing it as you have is triggering this.

Anyway, in this case I think you need to:

- Remove `picmo` from the `transpile` array.
- Use a dynamic import to import PicMo:

```
const { createPicker } = await import('picmo');
```

There is no error and you can then create a picker. See my forked CodeSandbox:
https://codesandbox.io/s/zen-galois-s406sl?file=/pages/index.vue

I have no experience with Nuxt so this may not be the "Nuxt way" to do this, but I did get the picker to render. Hope this helps.
