### ISSUE TITLE
Picmo down using CDN

### ISSUE THREAD

**Issue by ottho** [joeattardi/picmo#232]
Hi!
All my Picmo integration seems to be down using
`<script src="https://unpkg.com/picmo@latest/dist/umd/picmo.js"></script>`

Result in error:
`GET https://unpkg.com/picmo@5.5.0/dist/umd/picmo.js net::ERR_ABORTED 404`

**Comment by joeattardi** [comment]
Working on publishing an updated version that should resolve this, in the meantime you can use the previous version directly:

https://unpkg.com/picmo@5.4.2/dist/umd/picmo.js

Apologies for the inconvenience!

**Comment by ottho** [comment]
No worries, happy it's temporary.
Thanks for the (amazing) work 💯

**Comment by joeattardi** [comment]
Hey, sorry again for the UMD problem. I just pushed out a new release that fixes the issues (hopefully)! but the URL for the UMD distribution has changed slightly. See [here](https://picmojs.com/docs/getting-started/installation#from-a-cdn-umd) for details (TLDR: it's `index.js` instead of `picmo.js` now).

Please feel free to re-open or let me know if there are still problems. I did a quick test with the UMD CDN distribution and it seems to be working.
