### ISSUE TITLE
Dark theme not working

### ISSUE THREAD

**Issue by typhoon11** [joeattardi/picmo#235]
I enabled the dark theme for the picker, but the picker background became completely transparent, but it's okay with a white theme.
![image](https://user-images.githubusercontent.com/66431066/185355007-744c5c0b-4db5-4e52-9e2f-d19355bdf9ca.png)

**Comment by joeattardi** [comment]
Can you share a code example showing the problem? A screenshot is not enough to go by.

**Comment by typhoon11** [comment]
Never mind sorry for the late reply. In the documentation it was written that for themes the available strings are whiteTheme, darkTheme. So i used as darkTheme string but it was giving a transparent background then I later changed it to dark and it worked, it might be a error in the documentation or I mistaken something

**Comment by joeattardi** [comment]
These aren't raw string values, rather they are named exports from the picmo package. 

Using the raw string 'dark' does work currently since that's the underlying class name, but if that class name changes in the future it will break for you. 

By using the darkTheme export, you'll be guaranteed to always have the correct class name.

**Comment by joeattardi** [comment]
See https://picmojs.com/docs/usage/themes#specifying-a-theme
