### ISSUE TITLE
Not completely mobile friendly.

### ISSUE THREAD

**Issue by typhoon11** [joeattardi/picmo#236]
The picker when used on phone feels a little too big, so when the picker is used on phone it should make the sizes small in accordance to the phone screen width.

**Comment by joeattardi** [comment]
Thanks for the feedback. 

The previous mobile view was problematic for some users so it was removed pending a redesign at some point in the future.

Since major mobile OSes all have integrated emoji picker this has lower priority at the moment. 

You can always add custom CSS rules to try to adapt a mobile view that works for you.
