### ISSUE TITLE
"Smiling face" style issue

### ISSUE THREAD

**Issue by levipadre** [joeattardi/picmo#242]
https://jsfiddle.net/mafkc5sn/1/

For some reason this emoji character is not styled (third row middle).  I haven't checked all of them, I just spotted this one.

**Comment by joeattardi** [comment]
On my system, the picker renders OK, but that particular emoji renders wrong in the text field, is that what you're seeing?

The default system font, on some operating systems, do not render all emojis correctly. I'm really not sure why. Anyway, you need to use the system emoji font. This differs per platform of course, but this is what I use in the picker itself and it seems to work well:

```
font-family: "Segoe UI Emoji", "Segoe UI Symbol", "Segoe UI", "Apple Color Emoji", "Twemoji Mozilla",
    "Noto Color Emoji", "EmojiOne Color", "Android Emoji"
```

In your jsfiddle, I set this font family property on the input field, and then the emoji renders correctly.

I will add a section to the documentation about this, sorry for the confusion. Hope this fixes your issue!

**Comment by square-theme** [comment]
Thanks you for the quick response. It's clear, however I can't use a different font family for this input field. Every website has a style, which includes font family. The input field won't be using only for emojis but for normal text as well, like a chat input field. Any other way to solve this?

**Comment by joeattardi** [comment]
Unfortunately there isn't another way with native emojis. 

Keep in mind that the system "emoji font" has regular glyphs as well, so text typed in the field will still be readable. 

But unfortunately you can't use an arbitrary font in this case because other fonts do not always have all the necessary emoji glyphs. 

[This article](https://nolanlawson.com/2022/04/08/the-struggle-of-using-native-emoji-on-the-web/) describes it in more detail. 

Keep in mind that emojis are just Unicode code points, and like any other they won't render as expected if no glyph is defined. 

Your alternative is to use Twemoji, however that won't work with a native <input> at all since they are just SVG or PNG images. You'd have to use a contenteditable element for that.

**Comment by square-theme** [comment]
Thanks, it's fine now! For a moment I forgot that I can define multiple font families (mine first, than emoji ones).
