### ISSUE TITLE
Suggestions + error

### ISSUE THREAD

**Issue by fanthomas** [joeattardi/picmo#52]
I would like to thank you for this, it's really cool ! :)

My suggestions after implementation:

- Put the "emoji-button-3.0.3.min.js" file, in the source.zip in the future for releases. It's easier to update for large websites. Also name it always the same "emoji-button.min.js".
![image](https://user-images.githubusercontent.com/22766668/80867014-2ad5f400-8c92-11ea-8ecb-b364b0c8c715.png)

- Some emojies go outside the grid which creates a scrollbar in X. Could be cool to be able to control column properties tho.
![image](https://user-images.githubusercontent.com/22766668/80867174-f9a9f380-8c92-11ea-95d1-ff9434aa4880.png)

- I have an error in the console when I hide the searchBar (showSearch: false).
![image](https://user-images.githubusercontent.com/22766668/80912700-21ef2c00-8d3f-11ea-9e02-3b61dc78cfc9.png)
**Solution** : Goes away when I add "autoFocusSearch: false". Logic ! 
So maybe should set "autoFocusSearch" to "false" automatically if "showSearch" is set to "false".

Best regards mate !

**Comment by joeattardi** [comment]
Hey, sorry for the late response on this. Like, really late. Things have been busy lately!

The error in the console when `showSearch` is `false` should be fixed in the latest version. As for the emoji going outside the grid, what OS are you on? It looks like your platform doesn't support some of the compound emojis. For example, the Pilot emoji is a combination of the man emoji and the plane emoji. For some reason, on your system they are being displayed separately.

Does this display as a pilot on your system? 👨‍✈️

**Comment by fanthomas** [comment]
Hi man !

No worries, that's ok :) !

Yeah I saw in the new version that you corrected the `showSearch false` problem. 

My OS is **Windows 10 Pro 64 bits** and the browser is **Google Chrome** latest version. I see what you mean, it's weird because I have the most compatible bundle, it's not like I have safari on mac (as a web dev, I'm very irritated by this one lol).

And yeah, the pilot displays itself correctly on my system :

![image](https://user-images.githubusercontent.com/22766668/85705207-4f25de00-b6e1-11ea-9ed3-0155bd8e77a1.png)

Have a great day ! ✌

**Comment by joeattardi** [comment]
There are some known issues with emoji rendering still, particularly with Chrome.
